// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import("element-plus/es")["ElButton"];
  const ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
  const ElCol: typeof import("element-plus/es")["ElCol"];
  const ElForm: typeof import("element-plus/es")["ElForm"];
  const ElFormItem: typeof import("element-plus/es")["ElFormItem"];
  const ElInput: typeof import("element-plus/es")["ElInput"];
  const ElProgress: typeof import("element-plus/es")["ElProgress"];
  const ElResult: typeof import("element-plus/es")["ElResult"];
  const ElRow: typeof import("element-plus/es")["ElRow"];
  const ElStep: typeof import("element-plus/es")["ElStep"];
  const ElSteps: typeof import("element-plus/es")["ElSteps"];
  const ElTooltip: typeof import("element-plus/es")["ElTooltip"];
}
export {};
