// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElResult: typeof import("element-plus/es")["ElResult"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElStep: typeof import("element-plus/es")["ElStep"];
    ElSteps: typeof import("element-plus/es")["ElSteps"];
    FormContainer: typeof import("./src/components/login/FormContainer.vue")["default"];
    LoginForm: typeof import("./src/components/login/LoginForm.vue")["default"];
    SignInForm: typeof import("./src/components/login/SignInForm.vue")["default"];
    SignUpAccountForm: typeof import("./src/components/login/SignUpAccountForm.vue")["default"];
    SignUpComplete: typeof import("./src/components/login/SignUpComplete.vue")["default"];
    SignUpForm: typeof import("./src/components/login/SignUpForm.vue")["default"];
    SignUpPhone: typeof import("./src/components/login/SignUpPhone.vue")["default"];
    SwitchForm: typeof import("./src/components/login/SwitchForm.vue")["default"];
    ZpButton: typeof import("./src/components/login/ZpButton.vue")["default"];
  }
}

export {};
